### ISSUE TITLE
Can't save videos with pygame

### ISSUE THREAD

**Issue by RTunsi** [theRealProHacker/PyGameRecorder#10]
Hello,

I am trying to save a video when using pygame. I followed the instructions in README by downloading ffmpeg and adding the code
```
recording = recorder.get_single_recording() 
save_recordings(recording,("my_recording","mp4"))
```

However, I am getting the following error:
```
Traceback (most recent call last):
  File "C:\Users\raltunisi\.github\project\src\main.py", line 183, in <module>
    main()
  File "C:\Users\raltunisi\.github\project\src\main.py", line 175, in main
    recorder.save_recordings(recording, ("my_recording","mp4"))
  File "C:\Users\raltunisi\.github\project\.venv\Lib\site-packages\pygame_screen_record\ScreenRecorder.py", line 40, in inner
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raltunisi\.github\project\.venv\Lib\site-packages\pygame_screen_record\ScreenRecorder.py", line 430, in save_recordings
    saver = RecordingSaver(self.recordings, key, save_dir, blocking)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raltunisi\.github\project\.venv\Lib\site-packages\pygame_screen_record\ScreenRecorder.py", line 554, in __init__
    assert os.path.isdir(self.save_dir), f"save_dir has to be a directory: " + str(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: isdir: s should be string, bytes, os.PathLike or integer, not tuple
```
  
So I changed the input to a string:
```
recording = recorder.get_single_recording() 
save_recordings(recording,"my_recording.mp4"))
```

And got this error:
```
Traceback (most recent call last):
  File "C:\Users\raltunisi\.github\project\src\main.py", line 197, in <module>
    main()
  File "C:\Users\raltunisi\.github\project\src\main.py", line 183, in main
    recorder.save_recordings(recording, "recording.mp4")
  File "C:\Users\raltunisi\.github\project\.venv\Lib\site-packages\pygame_screen_record\ScreenRecorder.py", line 40, in inner
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raltunisi\.github\project\.venv\Lib\site-packages\pygame_screen_record\ScreenRecorder.py", line 430, in save_recordings
    saver = RecordingSaver(self.recordings, key, save_dir, blocking)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raltunisi\.github\project\.venv\Lib\site-packages\pygame_screen_record\ScreenRecorder.py", line 554, in __init__
    assert os.path.isdir(self.save_dir), f"save_dir has to be a directory: " + str(
AssertionError: save_dir has to be a directory: recording.mp4
```

Adding a directory does not change the outcome, the error is still the same.  For testing purposes, I removed the following line `assert os.path.isdir(self.save_dir), f"save_dir has to be a directory: " + str( ` but I get the following error
```
Exception in thread Thread-2 (_save):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\raltunisi\.github\project\.venv\Lib\site-packages\pygame_screen_record\ScreenRecorder.py", line 563, in _save
    os.chdir(self.save_dir)
FileNotFoundError: [WinError 2] The system cannot find the file specified: './videos/recording.mp4'  
```

I am not really sure, how I can resolve this issue. Any help is really appreciated.

**Comment by theRealProHacker** [comment]
Hi @RTunsi, you closed this issue as completed. 

If this is indeed fixed, for future reference, it would be nice if you document what the problem was and how you fixed it.

If it's not fixed, then maybe try something like this:
```py
recorder.save_recordings(recording,"mp4", "videos")
```

This will save the recordings as `recording_{index}.mp4` in the `videos` directory. If you only want to save a single recording, do this instead:

```py
recorder.get_single_recording().save(("recording", "mp4"))
```

In hindsight, I do realize that the API could have been designed better to allow `.save("recording", "mp4")`. So, I'll keep that in mind for a future feature release.
